version: '3'
services:
  myapp-web:
    build: .
    container_name: myapp-web
    image: my-php:7.4-apache
    ports:
      - "80:80"
    volumes:
      - ../html:/var/www/html

  mariadb:
    container_name: mariadb
    image: mariadb:10.5.4
    environment:
      MYSQL_DATABASE: test_db
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_password
      MYSQL_ROOT_PASSWORD: test_root_password
    volumes:
      - dbsocket:/var/run/mysqld

  myapp-pma:
    container_name: mariadb
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: test_hosst
      PMA_USER: test_user
      PMA_PASSWORD: test_password
    ports:
      - "8080:80"

volumes:
  dbsocket:
